"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import { useAuth } from "../hooks/useAuth";
import { useRouter } from "next/navigation";
import { supabase } from "../lib/supabaseClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = useAuth();
  const router = useRouter();

  const handleLogout = async () => {
    await supabase.auth.signOut();
    router.push("/");
  };

  return (
    <html lang="en">
      <head>
        <title>CX Lead Onboarding | CookUnity</title>
        <meta name="description" content="Generated by CookUnity CS Team" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f8f8f8]`}
      >
        <div className="flex min-h-screen">
          <Sidebar />
          <main className="flex-1">
            {user && (
              <header className="bg-[#2C282B] text-[#F5C027] p-4 flex justify-between items-center">
                <div></div>
                <div className="flex items-center gap-4">
                  <span>Welcome, {user.name || user.email}</span>
                  <button onClick={handleLogout} className="bg-[#ffc84e] text-black px-4 py-2 rounded-full hover:bg-[#ffb81c]">
                    Logout
                  </button>
                </div>
              </header>
            )}
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
